cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - check

test:
  stage: test
  image: blocknetdx/devbuilds:electron-tests
  script:
    - "npm install --no-audit"
    - "npm run test-headless"

build_linux:
  stage: build
  image: electronuserland/builder:latest
  script:
    - "npm install --no-audit"
    - "npm run download-binaries-linux"
    - "npm run build-native-linux2"
  artifacts:
    name: "XLite-$CI_COMMIT_REF_NAME-linux"
    paths:
      - dist-native/*.AppImage

build_win:
  stage: build
  image: electronuserland/builder:wine
  script:
    - "npm install --no-audit"
    - "npm run download-binaries-win"
    - "npm run build-native-win"
  artifacts:
    name: "XLite-$CI_COMMIT_REF_NAME-win"
    paths:
      - dist-native/*.exe
      - dist-native/*.zip

build_mac:
  stage: build
  image: blocknetdx/devbuilds:blockdx-gitlab-mac
  script:
    - "npm install --no-audit"
    - "npm run download-binaries-mac"
    - "chmod +x bin/mac/Cloudchains-SPV"
    - "npm run build-native-mac"
  artifacts:
    name: "XLite-$CI_COMMIT_REF_NAME-mac"
    paths:
      - dist-native/mac/XLite.app

check_artifacts:
  stage: check
  image: ubuntu:bionic
  script:
    - "set -- dist-native/XLite-*-linux.AppImage && [[ -f \"$1\" ]]"
    - "set -- dist-native/XLite-*-win.exe && [[ -f \"$1\" ]]"
    - "set -- dist-native/XLite-*-win-x64.zip && [[ -f \"$1\" ]]"
    - "set -- dist-native/mac/XLite.app && [[ -d \"$1\" ]]"
